version: '3'
services:
  db:
    image: 'mariadb:10'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - '~/dev-envrionnement/docker/mysql/mysql_bdd:/var/lib/mysql'
      - '~/dev-envrionnement/docker/mysql/mysql_conf:/etc/mysql/conf.d'
  maildev:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '1080:8025'
  redis:
    image: redis
    ports:
      - '6379:6379'
